### ISSUE TITLE
 could not find function "generate_network"

### ISSUE THREAD

**Issue by SunnyWit** [brielin/bimmer#24]
Hi, I install "bimmer" package and run code according to the test-fit-model:
generate_network(D = 3, g = 1)

it shows the error:
Error in generate_network(D = 3, g = 1) : 
  could not find function "generate_network"

How can I solve this problem?

Thanks a lot!

**Comment by SunnyWit** [comment]
I try the other function in "bimmer" package,it also shows the similar question:
could not find function "XX"

**Comment by brielin** [comment]
Hi SunnyWit,

Are you trying to use the function or run the tests? You should be able to run the tests using the instructions in the README. The functions for data simulation aren't exported, so to use them you will have to either load them with devtools or access them with `:::`.

Cheers,
Brielin

**Comment by SunnyWit** [comment]
Hi Brielin, Thanks a lot for your advice.  I added :::before the function,it works well.
